analytics: {}
color:
  brandColors:
    - '#C8B0B0'
    - '#000000'
    - '#888068'
    - '#000000'
    - '#F0D090'
  brandStrength: 0.739865
  lightness: 0.008413
  rhythmicContrast: 0.724308
  saturation: 0.374594
cta: {}
layout_spectrum: 0.055099724817650686
name: DedySahat
opengraph: {}
purpose: {}
typography_spectrum: 0.452703
